#!/bin/bash

# $assign = ASSIGNMENT

if [[ "$#" -ne 1 ]];
then
   echo "Usage: getTests <assignment>"
   echo "Example of <assignment>: 'Exercise8'"

else
   assign=$1
   p=~kmammen-grader/evaluations/W20/357/$assign/tests

   # ***** CORE TESTS *****

   CORE=$p/core

   if [ -d "$CORE" ]
   then
      touch core.tests

      echo -n "Value: " >> core.tests
      cat $CORE/value >> core.tests
      echo "" >> core.tests

      while IFS= read -r line ;
      do
         DESC=$CORE/$line/description

         echo "$line:" >> core.tests
         cat $DESC >> core.tests
         echo "" >> core.tests
      done < $CORE/testList
   fi

   # ***** FEATURE TESTS *****

   FEAT=$p/feature

   if [ -d "$FEAT" ]
   then
      touch feat.tests

      while IFS= read -r line;
      do
         VAL=$FEAT/$line/value
         DESC=$FEAT/$line/description

         echo -n "$line: " >> feat.tests
         cat $VAL >> feat.tests
         cat $DESC >> feat.tests
         echo "" >> feat.tests
      done < $FEAT/testList
   fi

fi
