#!/bin/bash

# $assign : ASSIGNMENT
# $@      : files to submit

if [[ "$#" -lt 2 ]];
then
   echo "Usage: turnin <option> <assignment> <files to submit>";
   echo "<option> = nothing if exercise, '-p' if project";
   echo "Example of <assignment>: 'Exercise8'";
else
   if [[ $1 == "-p" ]];
   then
      shift
      assign=$1
      shift

      zip $assign.zip $@
      handin kmammen-grader $assign $assign.zip
   else
      assign=$1
      shift
      zip $assign.zip $@
      handin kmammen-grader $assign-Section5 $assign.zip
   fi
fi
